version: '3.7'
services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - "6543:5432"

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: [ "/docker/app.sh" ]
    ports:
      - "9000:8000"

  celery:
    build:
      context: .
    container_name: booking_celery
    command: [ "/docker/celery.sh", "celery" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: booking_flower
    command: [ "/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - "5555:5555"